name = "cookie-cloudflare"
main = "dist/app.mjs"
minify = true
compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]
[vars]
CACHE_MAX_AGE = "3600"
# BASE_URL = ''
# CLOUDFLARE_ZONE_ID = ''
# CLOUDFLARE_API_KEY = ''
# CLOUDFLARE_EMAIL = ''

[[r2_buckets]]
binding = "R2"
bucket_name = "cookie-cloudflare"

# [[kv_namespaces]]
# binding = "KV"
# id = "2e7369529f5e441fb1159e4a4377aeef"

[env.dev]
# Development environment configuration
main = "src/app.ts"
minify = false

compatibility_date = "2026-01-01"
compatibility_flags = ["nodejs_compat"]

[[env.dev.r2_buckets]]
binding = "R2"
bucket_name = "cookie-cloudflare"

# [[env.dev.kv_namespaces]]
# binding = "KV"
# id = "2e7369529f5e441fb1159e4a4377aeef"

[env.dev.vars]
CACHE_MAX_AGE = '60'
BASE_URL = ''
CLOUDFLARE_ZONE_ID = ''
CLOUDFLARE_API_KEY = ''
CLOUDFLARE_EMAIL = ''

[observability]
enabled = true
head_sampling_rate = 1 # optional. default = 1.
